### List all messages
GET http://localhost:3000/msg


### Create a new message
POST http://localhost:3000/msg
content-type: application/json

{
    "content": 123
}


### Get a particular message
GET http://localhost:3000/msg/121212